'use strict';
/**
 * Textos do site (PT e EN). Foco: engenharia de dados + BI + IA aplicada (data warehouse em PostgreSQL/DuckDB, painéis,
 * chatbots no WhatsApp). Só afirma o que o Felipe confirmou ou o que está no LinkedIn/materiais da ProxyUS:
 * 9+ anos, 20+ clientes ativos, 5+ ERPs integrados. Sem números de resultado inventados.
 */
module.exports = SITE => ({
  pt: {
    lang: 'pt-BR', alt: 'en', altUrl: SITE + '/en/', url: SITE + '/', og: 'pt_BR',
    title: 'Engenheiro de Dados e BI em Londrina | Data Warehouse, Dashboards e Chatbots com IA | Felipe Marinho',
    desc: 'Felipe Marinho, Engenheiro de Dados com 9+ anos em Londrina. Data warehouse (PostgreSQL, DuckDB), dashboards de BI e chatbots com IA no WhatsApp que conversam com os dados da sua empresa. Remoto, UTC-3.',
    skip: 'Ir para o conteúdo',
    switchLabel: 'EN', switchTitle: 'Read in English',
    term: ['whoami', 'felipe_marinho // engenheiro_de_dados', 'stack', 'postgres duckdb python dbt bi ia', 'status', 'aberto a novos projetos'],
    h1a: 'Seus dados organizados,', h1b: 'em painéis e no WhatsApp.',
    sub: 'Sou Felipe Marinho, Engenheiro de Dados com 9+ anos. Monto <b>data warehouse</b> (PostgreSQL, DuckDB), <b>painéis de BI</b> e <b>chatbots com IA</b> que respondem sobre os dados da sua empresa, sem planilha paralela e sem esperar relatório.',
    cta1: 'Falar no WhatsApp', cta2: 'Ver LinkedIn', cta3: 'Enviar e-mail',
    waText: 'Olá Felipe, vi seu site e quero conversar sobre dados.',
    badges: ['9+ anos em dados', 'PostgreSQL · DuckDB · Python', 'BI · Chatbots com IA', 'Londrina/PR · remoto UTC-3'],
    probH: 'O problema', probP: 'Os dados estão espalhados no ERP, em planilhas e em vários sistemas. Todo número vira pedido de relatório, a diretoria espera dias e ninguém confia 100% no que vê. Enquanto isso, o atendimento depende de gente respondendo as mesmas perguntas no WhatsApp.',
    delH: 'O que eu entrego',
    del: [
      ['Data warehouse e pipelines', 'PostgreSQL e DuckDB como base analítica, com pipelines ETL/ELT (Python, dbt, Airflow) que juntam ERP, planilhas e APIs numa fonte única e confiável.'],
      ['BI e dashboards', 'Painéis claros em ProxyBI, Power BI e Qlik, atualizados sozinhos, para a diretoria acompanhar vendas, estoque e financeiro sem planilha paralela.'],
      ['Chatbots com IA no WhatsApp', 'Atendente que responde clientes 24h com as informações do seu negócio e passa para a equipe só o que precisa de gente. E um analista que responde perguntas sobre os dados da empresa.'],
      ['Integração de sistemas', 'ERPs, bancos de dados e APIs conectados numa base só. Já integrei mais de 5 ERPs.'],
      ['Qualidade, governança e modernização', 'Validação e reconciliação dos números, LGPD, controle de acesso e modernização de rotinas legadas (inclusive SQL Server) para uma base moderna.'],
    ],
    howH: 'Como trabalho',
    how: [['Diagnóstico', 'Mapeamento das fontes de dados, das perguntas do negócio e dos indicadores que importam.'], ['Base de dados', 'Modelagem e pipelines no PostgreSQL e no DuckDB, com números conferidos.'], ['Painéis e IA', 'Dashboards e chatbots construídos sobre a base, com acesso por permissão.'], ['Operação', 'Monitoramento, documentação e treinamento para o seu time assumir.']],
    pxH: 'Produtos próprios: ProxyUS', pxP: 'Na ProxyUS, em Londrina, transformei esse trabalho em três produtos para empresas:',
    px: [['AtendeAI', 'Atendente com IA no WhatsApp, 24h, que passa para a equipe quando precisa.'], ['BizBot', 'Converse com os dados da empresa no WhatsApp e receba o número, a comparação e o que mudou.'], ['ProxyBI', 'Todos os indicadores num só painel, com modo TV e relatórios agendados.']],
    pxLink: 'Conhecer a ProxyUS',
    stackH: 'Ferramentas',
    stack: ['PostgreSQL', 'DuckDB', 'Python', 'SQL', 'dbt', 'Airflow', 'ProxyBI', 'Power BI', 'Qlik Sense', 'WhatsApp API', 'Claude · GPT', 'Azure Data Factory', 'Databricks', 'BigQuery', 'SQL Server'],
    expH: 'Trajetória',
    exp: [
      ['hoje', 'Fundador · ProxyUS', 'AtendeAI, BizBot e ProxyBI: IA e dados para empresas, com 20+ clientes ativos.'],
      ['2025 → hoje', 'Engenheiro de Dados · AGGRANDIZE', 'Pipelines de dados, dashboards em Power BI, LGPD e controle de acesso. Contrato, remoto.'],
      ['2023 → 2025', 'Engenheiro de Dados · Localiza&Co', 'Python, dbt, Airflow e Google Cloud (BigQuery, Dataflow, Cloud Storage).'],
      ['2021 → 2023', 'Consultor de BI · Unidas', 'ETL e dashboards em QlikView e Qlik Sense. Prêmio de Prestador de Serviço Destaque da equipe de BI (2022).'],
      ['2017 → 2021', 'Analista de Sistemas · BRID Soluções', 'Desenvolvimento full-stack em PHP e BI para o agronegócio.'],
      ['antes', 'SAP GRC · Atos, e front-end · Agência Digital ICOMP', 'Base em sistemas, web e suporte técnico desde 2009.'],
    ],
    credH: 'Formação e certificações',
    cred: ['Bacharel em Ciência da Computação, com 1 ano de estudos na Kent State University (Ohio, EUA)', 'Databricks Fundamentals (Academy Accreditation)', 'Google Cloud Big Data and Machine Learning Fundamentals', 'Inglês avançado'],
    faqH: 'Perguntas frequentes',
    faq: [
      ['O que é um data warehouse e quando minha empresa precisa de um?', 'É uma base própria para análise, que reúne dados do ERP, de planilhas e de outros sistemas num lugar só, organizados para consulta e BI. Sua empresa precisa quando os relatórios demoram, cada área tem um número diferente ou o ERP fica lento por causa de consultas pesadas.'],
      ['PostgreSQL ou DuckDB: qual usar para análise de dados?', 'PostgreSQL é ótimo como banco central, com muitos usuários e atualizações. DuckDB é muito rápido para análise sobre grandes volumes e roda sem servidor pesado. Em muitos projetos uso os dois: PostgreSQL para a operação e DuckDB como motor analítico dos painéis.'],
      ['Como funciona um chatbot com IA no WhatsApp ligado aos dados da empresa?', 'No atendimento (AtendeAI), a IA responde clientes com as informações do seu negócio e passa para a equipe quando precisa. Na gestão (BizBot), o dono pergunta em português, como "quanto vendi hoje?", e recebe o número com comparação e explicação. Cada pessoa vê só os dados que tem permissão de ver.'],
      ['Você integra com o ERP que minha empresa usa?', 'Já integrei mais de 5 ERPs. Conte qual sistema você usa e eu confirmo como conectar, normalmente por banco de dados ou API.'],
      ['Você atende empresas de fora de Londrina ou do Brasil?', 'Sim. Trabalho remoto no fuso UTC-3, com sobreposição total ao horário comercial dos EUA e da Europa, e inglês avançado.'],
      ['Como começar?', 'Chame no WhatsApp ou por e-mail contando qual relatório, número ou atendimento hoje dá mais trabalho. Respondo com os próximos passos e o que preciso para um diagnóstico.'],
    ],
    ctaH: 'Quer seus dados e seu atendimento trabalhando por você?', ctaP: 'Conte o cenário em duas linhas. Respondo rápido.',
    foot: 'Londrina, Paraná, Brasil · UTC-3',
  },
  en: {
    lang: 'en', alt: 'pt-BR', altUrl: SITE + '/', url: SITE + '/en/', og: 'en_US',
    title: 'Data Engineer and BI Developer | Data Warehouse, Dashboards and AI Chatbots | Felipe Marinho',
    desc: 'Felipe Marinho, Data Engineer with 9+ years. Data warehouses (PostgreSQL, DuckDB), BI dashboards and AI chatbots on WhatsApp that answer questions about your company data. Remote from Brazil, UTC-3.',
    skip: 'Skip to content',
    switchLabel: 'PT', switchTitle: 'Ler em português',
    term: ['whoami', 'felipe_marinho // data_engineer', 'stack', 'postgres duckdb python dbt bi ai', 'status', 'open to new projects'],
    h1a: 'Your data organized,', h1b: 'in dashboards and on WhatsApp.',
    sub: 'I am Felipe Marinho, a Data Engineer with 9+ years. I build <b>data warehouses</b> (PostgreSQL, DuckDB), <b>BI dashboards</b> and <b>AI chatbots</b> that answer questions about your company data, with no side spreadsheets and no waiting for reports.',
    cta1: 'Message on WhatsApp', cta2: 'View LinkedIn', cta3: 'Send an email',
    waText: 'Hi Felipe, I saw your website and would like to talk about data.',
    badges: ['9+ years in data', 'PostgreSQL · DuckDB · Python', 'BI · AI chatbots', 'Remote from Brazil, UTC-3'],
    probH: 'The problem', probP: 'Data lives in the ERP, in spreadsheets and in several systems. Every number becomes a report request, leadership waits days and nobody fully trusts what they see. Meanwhile, customer service depends on people answering the same questions on WhatsApp.',
    delH: 'What I deliver',
    del: [
      ['Data warehouse and pipelines', 'PostgreSQL and DuckDB as the analytics base, with ETL/ELT pipelines (Python, dbt, Airflow) that bring ERP, spreadsheets and APIs into a single trustworthy source.'],
      ['BI and dashboards', 'Clear dashboards in ProxyBI, Power BI and Qlik, refreshed automatically, so leadership tracks sales, inventory and finance without side spreadsheets.'],
      ['AI chatbots on WhatsApp', 'An assistant that answers customers 24/7 with your business information and hands off to your team only what needs a human. And an analyst that answers questions about company data.'],
      ['Systems integration', 'ERPs, databases and APIs connected into one base. I have integrated more than 5 ERPs.'],
      ['Quality, governance and modernization', 'Validation and reconciliation of numbers, LGPD compliance, access control and modernization of legacy routines (including SQL Server) to a modern base.'],
    ],
    howH: 'How I work',
    how: [['Assessment', 'Mapping data sources, business questions and the indicators that matter.'], ['Data foundation', 'Modeling and pipelines on PostgreSQL and DuckDB, with verified numbers.'], ['Dashboards and AI', 'Dashboards and chatbots built on the base, with permission-based access.'], ['Operations', 'Monitoring, documentation and training so your team can take over.']],
    pxH: 'My own products: ProxyUS', pxP: 'At ProxyUS, in Londrina, Brazil, I turned this work into three products for businesses:',
    px: [['AtendeAI', 'AI assistant on WhatsApp, 24/7, that hands off to your team when needed.'], ['BizBot', 'Chat with your company data on WhatsApp and get the number, the comparison and what changed.'], ['ProxyBI', 'All your KPIs in a single dashboard, with TV mode and scheduled reports.']],
    pxLink: 'Visit ProxyUS',
    stackH: 'Tools',
    stack: ['PostgreSQL', 'DuckDB', 'Python', 'SQL', 'dbt', 'Airflow', 'ProxyBI', 'Power BI', 'Qlik Sense', 'WhatsApp API', 'Claude · GPT', 'Azure Data Factory', 'Databricks', 'BigQuery', 'SQL Server'],
    expH: 'Track record',
    exp: [
      ['now', 'Founder · ProxyUS', 'AtendeAI, BizBot and ProxyBI: AI and data for businesses, with 20+ active customers.'],
      ['2025 → now', 'Data Engineer · AGGRANDIZE', 'Data pipelines, Power BI dashboards, LGPD and access control. Contract, remote.'],
      ['2023 → 2025', 'Data Engineer · Localiza&Co', 'Python, dbt, Airflow and Google Cloud (BigQuery, Dataflow, Cloud Storage).'],
      ['2021 → 2023', 'BI Consultant · Unidas', 'ETL and dashboards in QlikView and Qlik Sense. Outstanding Service Provider award from the BI team (2022).'],
      ['2017 → 2021', 'Systems Analyst · BRID Soluções', 'Full-stack PHP development and BI for agribusiness.'],
      ['before', 'SAP GRC · Atos, and front-end · Agência Digital ICOMP', 'Foundation in systems, web and technical support since 2009.'],
    ],
    credH: 'Education and certifications',
    cred: ['B.Sc. in Computer Science, plus one year of study at Kent State University (Ohio, USA)', 'Databricks Fundamentals (Academy Accreditation)', 'Google Cloud Big Data and Machine Learning Fundamentals', 'Advanced English'],
    faqH: 'Frequently asked questions',
    faq: [
      ['What is a data warehouse and when does a company need one?', 'It is a dedicated base for analysis that brings data from the ERP, spreadsheets and other systems into one place, organized for querying and BI. A company needs one when reports take too long, each department has a different number, or the ERP slows down because of heavy queries.'],
      ['PostgreSQL or DuckDB: which one for data analysis?', 'PostgreSQL is great as a central database with many users and updates. DuckDB is very fast for analysis over large volumes and runs without a heavy server. In many projects I use both: PostgreSQL for operations and DuckDB as the analytics engine behind dashboards.'],
      ['How does an AI chatbot on WhatsApp connected to company data work?', 'For customer service (AtendeAI), the AI answers customers with your business information and hands off to your team when needed. For management (BizBot), the owner asks in plain language, like "how much did I sell today?", and gets the number with comparison and explanation. Each person only sees the data they are allowed to see.'],
      ['Do you integrate with the ERP my company uses?', 'I have integrated more than 5 ERPs. Tell me which system you use and I will confirm how to connect, usually through the database or an API.'],
      ['Do you work with companies outside Brazil?', 'Yes. I work remotely at UTC-3, with full overlap with US and European business hours, and advanced English.'],
      ['How do we start?', 'Message me on WhatsApp or by email telling me which report, number or customer service task costs you the most effort today. I reply with next steps and what I need for an assessment.'],
    ],
    ctaH: 'Want your data and customer service working for you?', ctaP: 'Describe the scenario in two lines. I reply fast.',
    foot: 'Londrina, Paraná, Brazil · UTC-3',
  },
});
